#!/bin/bash

USER_ID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)
SCRIPT_NAME=$(echo $0 | cut -d "." -f2)
LOGFILES=/tmp/$SCRIPT_NAME-$TIMESTAMP.log

echo "setup root password"
read -s dbpassword

#colors
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

VALIDATE_FUN(){
    if [ $1 -ne 0 ]
    then
        echo -e "$2 is $R FAILURE $N"
        exit 1
    else
        echo -e "$2 is $G SUCCESS $N"
    fi
}


if [ $USER_ID -eq 0 ]
then 
    echo "This is SUPER USER GO TO INSTALL PACKAGES"
else
    echo "THIS IS NOT SUPER USER PLEASE STOP OF THIS TO INSTALL PACKAGES"
    exit 1
fi

dnf install mysql-server -y &>>$LOGFILES
VALIDATE_FUN $? "INSTALLING MYSQL PACKAGE"

systemctl enable mysqld &>>$LOGFILES
VALIDATE_FUN $? "Mysql system enabaled"

systemctl start mysqld &>>$LOGFILES
VALIDATE_FUN $? "Mysql is start"

# mysql_secure_installation --set-root-pass ExpenseApp@1 &>>LOGFILES
# VALIDATE_FUN $? "Password setup to enter the db"

mysql -h 54.237.224.140 -u root -p -p${dbpassword} -e 'SHOW DATABASES;' &>>$LOGFILES
if [ $? -ne 0 ]
then 
    mysql_secure_installation --set-root-pass ${dbpassword} &>>$LOGFILES
    VALIDATE_FUN $? "setup root password"
else
    echo "Already Setup"
    exit 1
fi
    